Improves handling of `make check` dependency on python3
As Nick points out, if python3 detection is only at ./configure-time,
then a user could get a "you have no python3" warning then fix their
environment (`module load python`), but `make check` still won't work
until they configure again. I'd actually documented this already in H3
install guide, but nobody reads documentation, so principle of least
surprise should apply.

We already use a better alternative method in HMMER userguide, where
Makefile tests for presence of `rman` using the ungoogleable shell
subcommand `command -v`.

Now `make check`, `make dcheck` use the `command -v` test instead of
testing against a @PYTHON3@ configure output variable substitution.

diff --git a/Makefile.in b/Makefile.in
--- a/Makefile.in
+++ b/Makefile.in
@@ -75,7 +75,6 @@ COMPRESS = gzip
 AR       = @AR@
 RANLIB   = @RANLIB@
 INSTALL  = @INSTALL@
-PYTHON3  = @PYTHON3@
 
 
 # beautification magic, stolen from git
@@ -525,19 +524,13 @@ tests:  ${ALL_UTESTS}
 	${QUIET_SUBDIR0}miniapps ${QUIET_SUBDIR1} tests
 
 check:  ${ALL_UTESTS} .FORCE
-	@if ! test ${PYTHON3}; then\
-	    echo "No python3 found. 'make check' self test scripts are disabled.";\
-	    exit 1;\
-	fi
+	@command -v python3 >/dev/null 2>&1 || { echo >&2 "python3 is required for 'make check', but is not in your PATH. Aborting."; exit 1; }
 	${QUIET_SUBDIR0}miniapps  ${QUIET_SUBDIR1} check
 	${QUIET_SUBDIR0}testsuite ${QUIET_SUBDIR1} check
 
 # `make dcheck`: run developer testsuite, save output in testsuite/dcheck.report
 dcheck:
-	@if ! test ${PYTHON3}; then\
-	    echo "No python3 found. 'make dcheck' self test scripts are disabled.";\
-	    exit 1;\
-	fi
+	@command -v python3 >/dev/null 2>&1 || { echo >&2 "python3 is required for 'make check', but is not in your PATH. Aborting."; exit 1; }
 	${QUIET_SUBDIR0}testsuite   ${QUIET_SUBDIR1} dcheck
 
 pdf:
